In [2]:
import pandas as pd
df = pd.read_csv('simulation_sns/kobertopic_argument_topics.csv')
df.head()

,sim_id,condition,turn,point,topic_id,topic_label,topic_keywords,text,subclaim
0,42bb2787-7fce-4b44-98c3-681084cda2f3,authorless-2,1,1,2,소셜 미디어의 교육적 기능,"없음, , , , , , ,",인터넷은 교육적 자원으로서 중요한 역할을 합니다,"미성년자들은 소셜 미디어를 통해 다양한 정보와 지식을 습득할 수 있으며, 이는 그들..."
1,42bb2787-7fce-4b44-98c3-681084cda2f3,authorless-2,1,2,8,중독 문제 해결 방안,"없음, , , , , , ,",사회적 소통의 경험은 중요한 성장 과정입니다,소셜 미디어는 미성년자들이 다양한 사람들과 교류하며 의사소통 능력을 키울 수 있는 ...
2,42bb2787-7fce-4b44-98c3-681084cda2f3,authorless-2,1,3,-1,Noise (미분류),"없음, , , , , , ,",표현의 자유는 청소년에게도 중요한 권리입니다,소셜 미디어는 미성년자들이 자기 생각을 표현하고 자신을 드러낼 수 있는 플랫폼입니다...
3,42bb2787-7fce-4b44-98c3-681084cda2f3,authorless-2,2,1,28,예방과 교육의 지속 가능성,"없음, , , , , , ,",부정적인 영향은 교육과 자율적인 사용법으로 완화할 수 있습니다,"미성년자들이 소셜 미디어를 사용할 때 올바른 정보와 적절한 지원을 제공받으면, 부정..."
4,42bb2787-7fce-4b44-98c3-681084cda2f3,authorless-2,2,2,5,정보 보호와 가족의 역할,"없음, , , , , , ,",가정 내에서의 부모와의 협력은 효과적인 해결책이 될 수 있습니다,소셜 미디어 사용에 대한 현실적인 지침과 규칙을 설정하여 자녀와 부모 간의 대화를 ...

In [3]:
df[df['topic_id']==0]['text']

28                     또한, 법안은 기술의 빠른 발전 속도를 따라잡지 못할 것입니다
54                        미성년자의 자기 표현과 창의력 발휘를 제한할 수 있습니다
56                         디지털 시대에 필수적인 기술을 학습할 기회를 억제합니다
69          법적 제한은 유연성이 떨어지며 변화하는 기술 환경에 발 빠르게 대응하기 어렵습니다
78      법적 규제는 오히려 기술의 발전과 적응을 늦추고, 미성년자들이 필요한 기술을 습득할...
                              ...
1708         둘째, 유연한 법안 및 교육 프로그램 혼합은 정책의 일관성을 저해할 수 있습니다
1730          제한적인 접근은 디지털 기술에 대한 미성년자들의 이해도를 떨어뜨릴 수 있습니다
1734                              법적 제한은 역효과를 초래할 수도 있습니다
1766                        셋째, 제도적 금지는 우회되기 쉽고 실효성이 낮습니다
1768                            둘째, 법적 제한은 혁신을 저해할 수 있습니다
Name: text, Length: 155, dtype: object

In [4]:
df_animal = pd.read_csv('simulation_2/kobertopic_argument_topics.csv')
df_animal.head()

,sim_id,condition,turn,point,topic_id,topic_label,topic_keywords,text,subclaim
0,49e11e13-95b8-4415-a0ce-bb315072e4b7,authorless,1,1,-1,Noise (미분류),"없음, , , , , , ,",동물 실험은 인체에 미칠 영향을 예측하는 데 필수적입니다,"동물 모델은 인간의 생물학적 구조와 매우 유사한 특징을 가지고 있으며, 이를 통해 ..."
1,49e11e13-95b8-4415-a0ce-bb315072e4b7,authorless,1,2,7,혁신적인 치료법 개발,"없음, , , , , , ,",동물 실험은 과학적 발견의 기반을 마련합니다,"실험을 통해 얻은 데이터는 인간 생리학에 대한 이해를 심화시키고, 이는 질환에 대한..."
2,49e11e13-95b8-4415-a0ce-bb315072e4b7,authorless,1,3,11,임상 전 연구의 안전성,"없음, , , , , , ,",동물 실험은 최종 사용자에게 안전한 결과물을 제공하는 데 중요합니다,"새로운 치료법이나 약물이 실제로 인간에게 사용되기 전에, 가능한 부작용을 식별하고 ..."
3,49e11e13-95b8-4415-a0ce-bb315072e4b7,authorless,2,1,4,대체 기술의 제한,"없음, , , , , , ,",인공 장기나 컴퓨터 모델은 현재의 기술로는 아직 초기 단계입니다,"이러한 대체 방법들은 인체의 복잡한 생리적 반응을 완전히 재현할 수 없으며, 이는 ..."
4,49e11e13-95b8-4415-a0ce-bb315072e4b7,authorless,2,2,-1,Noise (미분류),"없음, , , , , , ,",동물 실험은 예측불가능한 문제점을 미리 식별하는 역할을 합니다,중증 질환 치료 연구에서는 예기치 않은 부작용이나 인체 반응을 조기에 발견하는 것이...